### PR TITLE
switched from using showdown to marked for markdown parsing

### PR DESCRIPTION
**Pull request by shacharRonZohar**
Solving issue #48,
it's possible some lines that are unrelated were cosmetically altered because of mismatched prettier settings, I did my best to clean them up to the old state.

Emoji parsing will need further handling

### CODE REVIEW

**Comment by yonatanmgr** [comment]
Hey, it seems the issue still exists in your deployment:
image

**Comment by shacharRonZohar** [comment]
@yonatanmgr 
Turns out GitHub can selectively render imgs as part of URI fragments according the user's dark mode preferance, and they control it via display none, that's why we were seeing 2 imgs, so I implemented something similar to theirs.

**Comment by shacharRonZohar** [comment]
So tailwind has a default setting where it sets list-style to none for ul, ol, and menu, so I applied a list-style:revert to all list elements rendered inside .markdown-body, which seems to have solved it.

We were importing the github markdown dark style exclusively, so I added conditional imports according to the user's preferance, which is unrelated but nice to have.

I did notice another thing, which I suspect might require more complex customized parsing (or integrating the actual parser github uses), where they turn [] into checkbox elements, which we aren't supporting currently.

ours:
checkmarks

actual:
checkmarks-actual

**Review by yonatanmgr — APPROVED** [review]
That seems to work great! Thank you for your efforts 👌

**Pull request merged**
