### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by DrVickie8**

### CODE REVIEW

**Review by yonatanmgr — CHANGES_REQUESTED** [review]
This looks good! Thank you so much.
Just one correction - maybe add yonatanmgr@gmail.com as a contact for me in addition to @yonmgr on Discord

**Comment by DrVickie8** [comment]
Sure. I'll add your email address too.

**Comment by DrVickie8** [comment]
I just made the changes @yonatanmgr

**Review by yonatanmgr — APPROVED** [review]
Thank you!

**Pull request merged**
